# Generated by Django 4.2 on 2025-02-07 10:51

import Admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_user_address_user_cnic_user_joining_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('session_photo', models.ImageField(blank=True, null=True, upload_to=Admin.models.session_photo_path)),
                ('registration_fee', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(blank=True, max_length=100, null=True)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=Admin.models.student_profile_photo_path)),
                ('cnic_photo', models.ImageField(blank=True, null=True, upload_to=Admin.models.student_cnic_photo_path)),
                ('degree_photo', models.ImageField(blank=True, null=True, upload_to=Admin.models.student_degree_photo_path)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('last_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('last_institution', models.CharField(blank=True, max_length=50, null=True)),
                ('Temp_address', models.TextField(blank=True, null=True)),
                ('Perm_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_fee', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('fee_paid', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_students', to='Admin.sessions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='Admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('studentsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='Admin.studentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Late Fee', 'Late fee'), ('New Entry', 'New Entry'), ('Deletion', 'Deletion'), ('New Fee', 'New Fee'), ('Updation', 'Updation')], max_length=10)),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.sessions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.student')),
            ],
        ),
    ]
