# Generated by Django 4.2 on 2025-04-26 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='area_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='form_of_inquiry',
            field=models.CharField(choices=[('Call', 'Call'), ('Message', 'Message'), ('Physical Visit', 'Physical Visit')], default='Call', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.sessions'),
        ),
    ]
