# Generated by Django 4.2 on 2025-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_lead_area_of_residence_lead_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inactive_reason',
            field=models.CharField(blank=True, choices=[('Freeze', 'Freeze'), ('Expelled', 'Expelled'), ('', 'None')], default='', max_length=10),
        ),
    ]
