# Generated by Django 4.2 on 2025-04-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_address_user_cnic_user_joining_date_and_more'),
        ('Admin', '0004_studentfee_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_students', to='authentication.user'),
        ),
    ]
