# Generated by Django 4.2 on 2025-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_student_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='final_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='per_installment_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='total_fee',
            field=models.IntegerField(),
        ),
    ]
