# Generated by Django 4.2 on 2025-07-31 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_installment_amount_alter_studentfee_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
