# Generated by Django 4.2 on 2025-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_student_created_at_alter_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='monthly_fee',
            field=models.IntegerField(blank=True, help_text='Monthly fee for monthly sessions', null=True),
        ),
        migrations.AddField(
            model_name='sessions',
            name='session_type',
            field=models.CharField(choices=[('time_period', 'Time Period Session'), ('monthly', 'Monthly Session')], default='time_period', max_length=15),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='monthly_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='next_monthly_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='fee',
            field=models.IntegerField(help_text='One-time fee for time period sessions'),
        ),
    ]
