# Generated by Django 4.2 on 2025-07-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_sessions_monthly_fee_sessions_session_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='fee',
            field=models.IntegerField(blank=True, help_text='One-time fee for time period sessions', null=True),
        ),
    ]
