# Generated by Django 4.2 on 2025-07-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_alter_sessions_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='monthly_fee',
        ),
        migrations.AlterField(
            model_name='sessions',
            name='fee',
            field=models.IntegerField(blank=True, help_text='Fee for all session types', null=True),
        ),
    ]
