# Generated by Django 4.2 on 2025-07-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_remove_sessions_monthly_fee_alter_sessions_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='monthly_fee',
        ),
    ]
