# Generated by Django 4.2 on 2025-08-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_remove_studentsession_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
