# Generated by Django 4.2 on 2025-08-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_redundant_payment_tables'),
        ('Admin', '0014_alter_notification_date'),
    ]

    operations = [
    ]
