# Generated by Django 4.2 on 2025-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_cleanup_orphaned_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Active', max_length=10),
        ),
    ]
