# Generated by Django 4.2 on 2025-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_alter_sessions_status_alter_student_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Late Fee', 'Late fee'), ('New Entry', 'New Entry'), ('Deletion', 'Deletion'), ('New Fee', 'New Fee'), ('Updation', 'Updation'), ('Monthly Renewal', 'Monthly Renewal')], max_length=20),
        ),
    ]
