# Generated by Django 4.2 on 2024-10-19 09:09

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.profile_photo_path),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Moderator'), (3, 'Teacher')], default=3),
        ),
    ]
